dist: xenial
sudo: enabled
language: minimal

install:
  - sudo apt-get update -y
  - sudo apt-get install -y cpanminus fatpack

script:
  - make deb

deploy:
  - provider: releases
    api_key:
      secure: "Lux2Bbw73NNtc6o5pB1WMvtyXKP8/pSaxLTgDEZWf/cQhYYzCVaFcfECi5cVIiScGuB8x6Xi3tD7TuLWCVlXNrc9FDLK2ERJoZ7icsEHt82PalYXQs0qiC/WzFWNSnoDsmoBJXSjZhjqORTUEw6R74I7yVHAxn9bC+4ghwUl/9n2ukNRGfjMOzxXer4qP/R5ioQenumY1uT5JVvdMAyAjk2TgzZjv5y55SdPoKVuO7utb0MT4naQ8MZoqm6f1yu9/LPcpyBuka6m5aLsh/gwQ728EjEZlVe17XpOR1QlFG9ZdU2JEqntHMmgce46LFG+UG7hWT/vxSnGcVVjb1DxVf2YYtKlkdospuTnXXFoEk93yOm4UsnGZ5uVaZ6lsQHIe/4ElDdnmCvGRGVqMNvn+yiT1H7uNlsfyU1ne1hWl9LNmRkwTdgORwEOFk+9EhwE9lCQaUHbbCH+PPyLs9mK9SWYla9PScRUwcbmPdsQa0clkKJGAQqNkzXcdHBFO0xNJG1VEMGbACd9bNSFGpWHncmTgaygk/zN1R4X6dFSLhUVQRp1nm7u7g75dxQylEukBF6N7A8mleQBouNXV5AdHtVX68LKSFS24+GMnDHC8xT4PJwmA+mARokwf0EniJzBGK8AuRTBihBqQ7CKorRIjL6yg7RS8xDKPc5slCMA+uw="
    file_glob: true
    file: output/*
    skip_cleanup: true
    on:
      repo: stigtsp/cjdns-hello
      tags: true
