#!/bin/sh -e

## from /usr/share/debhelper/autoscripts/postrm-systemd :

if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask cjdns-hello.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge cjdns-hello.service >/dev/null
		deb-systemd-helper unmask cjdns-hello.service >/dev/null
	fi
fi

exit 0
